# Goals
1. Import a dataset
2. Train a Classifier
3. Predict labe for new flower
4. Visualize the Tree

### Importing a Dataset
for this i am gonna use the built in dataset with sk-learn.

In [ ]:
from sklearn.datasets import load_iris

In [ ]:
iris = load_iris()
print(iris.feature_names)

In [ ]:
print(iris.data[0])

In [15]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [ ]:
for i in range(len(iris.target)):
    print (f"Example{i} : Label{iris.target[i]}, Feature{iris.data[i]}")

### Training a Classifier

First i am gonna divide the training data in to 2 parts:
1. The data that will be used to train the classifier
2. the data that will be used to test the classifier

In [14]:
import numpy as np

#### Training data
* the Setosa is at the index 0
* the versicolor is at the index 50
* the Virginica is at the index 100

In [16]:
test_idx = [0,50,100]
train_target = np.delete(iris.target, test_idx)
train_data = np.delete(iris.data, test_idx)

#### Testing Data

In [17]:
Test_target = iris.target[test_idx]
Test_data = iris.data[test_idx]

In [24]:
print(Test_data)

[[5.1 3.5 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.3 3.3 6.  2.5]]


### Predicting label for new Flower

In [18]:
from sklearn import tree

In [25]:
clf = tree.DecisionTreeClassifier()
clf.fit(train_data, train_target)

ValueError: Expected 2D array, got 1D array instead:
array=[3.5 1.4 0.2 4.9 3.  1.4 0.2 4.7 3.2 1.3 0.2 4.6 3.1 1.5 0.2 5.  3.6 1.4
 0.2 5.4 3.9 1.7 0.4 4.6 3.4 1.4 0.3 5.  3.4 1.5 0.2 4.4 2.9 1.4 0.2 4.9
 3.1 1.5 0.1 5.4 3.7 1.5 0.2 4.8 3.4 1.6 0.2 4.8 3.  0.1 4.3 3.  1.1 0.1
 5.8 4.  1.2 0.2 5.7 4.4 1.5 0.4 5.4 3.9 1.3 0.4 5.1 3.5 1.4 0.3 5.7 3.8
 1.7 0.3 5.1 3.8 1.5 0.3 5.4 3.4 1.7 0.2 5.1 3.7 1.5 0.4 4.6 3.6 1.  0.2
 5.1 3.3 1.7 0.5 4.8 3.4 1.9 0.2 3.  1.6 0.2 5.  3.4 1.6 0.4 5.2 3.5 1.5
 0.2 5.2 3.4 1.4 0.2 4.7 3.2 1.6 0.2 4.8 3.1 1.6 0.2 5.4 3.4 1.5 0.4 5.2
 4.1 1.5 0.1 5.5 4.2 1.4 0.2 4.9 3.1 1.5 0.2 5.  3.2 1.2 0.2 5.5 3.5 1.3
 0.2 4.9 3.6 1.4 0.1 4.4 3.  1.3 0.2 5.1 3.4 1.5 0.2 5.  3.5 1.3 0.3 4.5
 2.3 1.3 0.3 4.4 3.2 1.3 0.2 5.  3.5 1.6 0.6 5.1 3.8 1.9 0.4 4.8 3.  1.4
 0.3 5.1 3.8 1.6 0.2 4.6 3.2 1.4 0.2 5.3 3.7 1.5 0.2 5.  3.3 1.4 0.2 7.
 3.2 4.7 1.4 6.4 3.2 4.5 1.5 6.9 3.1 4.9 1.5 5.5 2.3 4.  1.3 6.5 2.8 4.6
 1.5 5.7 2.8 4.5 1.3 6.3 3.3 4.7 1.6 4.9 2.4 3.3 1.  6.6 2.9 4.6 1.3 5.2
 2.7 3.9 1.4 5.  2.  3.5 1.  5.9 3.  4.2 1.5 6.  2.2 4.  1.  6.1 2.9 4.7
 1.4 5.6 2.9 3.6 1.3 6.7 3.1 4.4 1.4 5.6 3.  4.5 1.5 5.8 2.7 4.1 1.  6.2
 2.2 4.5 1.5 5.6 2.5 3.9 1.1 5.9 3.2 4.8 1.8 6.1 2.8 4.  1.3 6.3 2.5 4.9
 1.5 6.1 2.8 4.7 1.2 6.4 2.9 4.3 1.3 6.6 3.  4.4 1.4 6.8 2.8 4.8 1.4 6.7
 3.  5.  1.7 6.  2.9 4.5 1.5 5.7 2.6 3.5 1.  5.5 2.4 3.8 1.1 5.5 2.4 3.7
 1.  5.8 2.7 3.9 1.2 6.  2.7 5.1 1.6 5.4 3.  4.5 1.5 6.  3.4 4.5 1.6 6.7
 3.1 4.7 1.5 6.3 2.3 4.4 1.3 5.6 3.  4.1 1.3 5.5 2.5 4.  1.3 5.5 2.6 4.4
 1.2 6.1 3.  4.6 1.4 5.8 2.6 4.  1.2 5.  2.3 3.3 1.  5.6 2.7 4.2 1.3 5.7
 3.  4.2 1.2 5.7 2.9 4.2 1.3 6.2 2.9 4.3 1.3 5.1 2.5 3.  1.1 5.7 2.8 4.1
 1.3 6.3 3.3 6.  2.5 5.8 2.7 5.1 1.9 7.1 3.  5.9 2.1 6.3 2.9 5.6 1.8 6.5
 3.  5.8 2.2 7.6 3.  6.6 2.1 4.9 2.5 4.5 1.7 7.3 2.9 6.3 1.8 6.7 2.5 5.8
 1.8 7.2 3.6 6.1 2.5 6.5 3.2 5.1 2.  6.4 2.7 5.3 1.9 6.8 3.  5.5 2.1 5.7
 2.5 5.  2.  5.8 2.8 5.1 2.4 6.4 3.2 5.3 2.3 6.5 3.  5.5 1.8 7.7 3.8 6.7
 2.2 7.7 2.6 6.9 2.3 6.  2.2 5.  1.5 6.9 3.2 5.7 2.3 5.6 2.8 4.9 2.  7.7
 2.8 6.7 2.  6.3 2.7 4.9 1.8 6.7 3.3 5.7 2.1 7.2 3.2 6.  1.8 6.2 2.8 4.8
 1.8 6.1 3.  4.9 1.8 6.4 2.8 5.6 2.1 7.2 3.  5.8 1.6 7.4 2.8 6.1 1.9 7.9
 3.8 6.4 2.  6.4 2.8 5.6 2.2 6.3 2.8 5.1 1.5 6.1 2.6 5.6 1.4 7.7 3.  6.1
 2.3 6.3 3.4 5.6 2.4 6.4 3.1 5.5 1.8 6.  3.  4.8 1.8 6.9 3.1 5.4 2.1 6.7
 3.1 5.6 2.4 6.9 3.1 5.1 2.3 5.8 2.7 5.1 1.9 6.8 3.2 5.9 2.3 6.7 3.3 5.7
 2.5 6.7 3.  5.2 2.3 6.3 2.5 5.  1.9 6.5 3.  5.2 2.  6.2 3.4 5.4 2.3 5.9
 3.  5.1 1.8].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.